# TODO: Find out if something needs to be changed in here in comparison to digiplan

exclude: 'docs|node_modules|vendors|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.5
    hooks:
      - id: jshint

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.244'
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["black"]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
      - id: flake8
        name: flake8
        args:
          - --max-line-length=120
          - --ignore=DAR101,DAR201,F821
        entry: flake8
        language: python
        types: [python]
      - id: pylint
        name: pylint
        entry: env DATABASE_URL=null env PROJ_LIB=null USE_DOCKER=null pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
